# Generated by Django 6.1 on 2026-08-30 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad del producto')),
                ('unidad_medida', models.CharField(help_text='Ej: kg, unidades, bolsas', max_length=50)),
                ('fecha_limite_retiro', models.DateTimeField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('RETIRADO', 'Retirado'), ('EXPIRADO', 'Expirado')], default='DISPONIBLE', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Retiro'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='core.lotealimento')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
