# Generated by Django 6.1 on 2026-08-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_limite', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='organizacion',
        ),
        migrations.DeleteModel(
            name='LoteAlimento',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
