# Generated by Django 4.2.30 on 2026-09-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alimento_remove_reserva_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
