# Generated by Django 4.2.30 on 2026-09-21 05:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_alimento_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=120)),
                ('rut_comercial', models.CharField(max_length=12, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizacionSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entidad', models.CharField(max_length=150)),
                ('personalidad_juridica', models.CharField(max_length=50, unique=True)),
                ('responsable', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='alimento',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alimento',
            name='categoria',
            field=models.CharField(choices=[('Frutas y Verduras', 'Frutas y Verduras'), ('Panadería y Pastelería', 'Panadería y Pastelería'), ('Lácteos', 'Lácteos'), ('Abarrotes', 'Abarrotes'), ('Otros', 'Otros')], max_length=50),
        ),
        migrations.CreateModel(
            name='ReservaDonacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Retiro'), ('Retirado', 'Retirado Conforme'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.alimento')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.organizacionsocial')),
            ],
        ),
        migrations.AddField(
            model_name='alimento',
            name='comercio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='core.comercio'),
        ),
    ]
